services:
  - type: web
    name: reelbite-api
    env: node
    plan: free
    buildCommand: npm install --prefix server
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
